import sys
import os
import time
# 获取当前文件的路径，并添加到 sys.path
current_dir = os.path.dirname(os.path.abspath(__file__))
sys.path.append(current_dir)

# 添加上一级目录，确保 speculative 可以被导入
sys.path.append(os.path.join(current_dir, "speculative"))

import torch
from torch.nn import Module
from logits_processor import LogitsProcessor, GreedyProcessor, MultinomialProcessor
from transformers.cache_utils import DynamicCache
from caching import prune_cache
from sparse_cache import apply_triforce_sparse
import printing as printing
from typing import List, Tuple, Optional


def max_fn(x: torch.Tensor) -> torch.Tensor:
    """
    Max function.
        x: input tensor.
    Returns:
        tensor norm(max(0, x)).
    """
    x_max = torch.where(x > 0, x, torch.zeros_like(x))
    x_max_sum = torch.sum(x_max, dim=-1, keepdim=True)
    return x_max / x_max_sum


def _cache_seq_len(cache):
    """Get sequence length from either DynamicCache or tuple cache."""
    if isinstance(cache, DynamicCache):
        if hasattr(cache, 'key_cache') and len(cache.key_cache) > 0:
            return cache.key_cache[0].shape[2]
        # Newer transformers: use get_seq_length()
        return cache.get_seq_length()
    if hasattr(cache, 'get_seq_length'):
        return cache.get_seq_length()
    return cache[0][0].size(-2)


@torch.no_grad()
def speculative_generate(
    inputs: List[int],
    drafter: Module,
    target: Module,
    tokenizer = None,
    gamma: int = 3,
    logits_processor: LogitsProcessor = MultinomialProcessor(0.7),
    max_gen_len: int = 40,
    eos_tokens_id: int | List[int] = 1,
    pad_token_id: int = 0,
    use_cache: bool = False,
    skip_sample_adjustment: bool = False,
    first_target: bool = True,
    debug: bool = False,
    use_greedy_sampler: bool = False,
    sparse_budget: Optional[int] = None,
    chunk_size: int = 8,
) -> Tuple[List[int], float]:
    """
    Generate text sequence using the speculative decoding algorithm.
    Implementation of Speculative Decoding. (https://arxiv.org/pdf/2211.17192.pdf)

    When sparse_budget is set, the drafter's KV cache is sparsified after prefill
    using TriForce's attention-based chunk selection (arXiv:2404.11912).

    Args:
        inputs (List[int]): input sequence of batch size 1.
        drafter (Module): drafter model.
        target (Module): target model.
        tokenizer: tokenizer (used for debugging).
        gamma (int): number of drafts generated by the drafter at each step.
        logits_processor (LogitsProcessor): logits processor for sampling.
        max_gen_len (int): maximum length of the generated sequence.
        eos_tokens_id (int or List[int]): end token id (could be multiple).
        pad_token_id (int): pad token id.
        use_cache (bool): whether to use cache.
        skip_sample_adjustment (bool): skip sample adjustment for rejected drafts.
        first_target (bool): run target model first for prefill.
        debug (bool): debug mode.
        use_greedy_sampler (bool): use greedy sampling.
        sparse_budget (int or None): if set, sparsify drafter cache to this budget.
        chunk_size (int): chunk size for sparse selection.

    Returns:
        List[int]: generated sequence.
        float: acceptance rate.
    """

    drafter_cache, target_cache = None, None

    drafts_accepted, drafts_speculated = .0, .0
    vocabulary_size = target.config.vocab_size
    stop_tokens = eos_tokens_id

    # prepare input tensor
    prompt_len = len(inputs)
    total_len = prompt_len + max_gen_len
    input_ids = torch.full((1, total_len), pad_token_id, dtype=torch.long, device=target.device)
    input_ids[0, :prompt_len] = torch.tensor(inputs, dtype=torch.long, device=target.device)

    tot_token_nums = prompt_len

    # Whether we are using sparse drafter cache
    use_sparse = sparse_budget is not None and sparse_budget < prompt_len
    # Tracks the actual sequence position for drafter (differs from cache size when sparse)
    drafter_pos_offset = 0  # actual_pos = cache_seq_len + drafter_pos_offset

    if first_target:
        # run the target model before the speculative algorithm
        Mp = target(
            input_ids=input_ids[..., :tot_token_nums],
            past_key_values=target_cache,
            use_cache=use_cache,
        )
        target_cache = Mp.past_key_values

        if use_greedy_sampler:
            t = torch.argmax(Mp.logits[..., -1, :], dim = -1)
        else:
            p_p = logits_processor(Mp.logits[..., -1, :])
            t = logits_processor.sample(p_p)
        input_ids[0, tot_token_nums] = t
        tot_token_nums += 1

        if t == stop_tokens:
            if debug:
                printing.end_token_found(0)
            return input_ids[0, prompt_len:tot_token_nums].tolist(), 0, 0

        if debug:
            printing.initial_step(t, tokenizer)

        # Drafter prefill
        Mq = drafter(
                input_ids=input_ids[..., :prompt_len],
                past_key_values=drafter_cache,
                use_cache=use_cache,
            )
        drafter_cache = Mq.past_key_values

        # Apply sparse selection to drafter cache
        if use_sparse:
            drafter_cache, original_len = apply_triforce_sparse(
                drafter_cache, sparse_budget, chunk_size
            )
            sparse_cache_len = _cache_seq_len(drafter_cache)
            drafter_pos_offset = original_len - sparse_cache_len
            # print(f"[Sparse] budget={sparse_budget}, original={original_len}, "
            #       f"sparse={sparse_cache_len}, offset={drafter_pos_offset}")

    step = 0
    while tot_token_nums < total_len:
        step += 1
        corrected_gamma = min(gamma, total_len - tot_token_nums - 1)
        if not use_greedy_sampler:
            q = torch.zeros((corrected_gamma, vocabulary_size), device=target.device)

        # generate gamma drafts
        hl = []
        current_position = tot_token_nums - 1

        for k in range(corrected_gamma):
            # Build position_ids for drafter
            if use_sparse:
                pos_id = current_position + k  # actual position in sequence
                position_ids = torch.tensor([[pos_id]], device=drafter.device)
            else:
                position_ids = None  # let model auto-compute

            Mq = drafter(
                input_ids=input_ids[..., current_position + k: current_position + k + 1],
                past_key_values=drafter_cache,
                use_cache=use_cache,
                position_ids=position_ids,
            )
            drafter_cache = Mq.past_key_values

            if use_greedy_sampler:
                xi = t = torch.argmax(Mq.logits, dim = -1)
            else:
                draft_probs = logits_processor(Mq.logits)[0]
                xi = logits_processor.sample(draft_probs)
                q[k] = draft_probs

            input_ids[0, current_position + 1 + k] = xi
            hl.append(xi)

        drafts_speculated += corrected_gamma

        # run target model on drafts
        assert _cache_seq_len(target_cache) == tot_token_nums - 1
        Mp = target(
            input_ids=input_ids[..., current_position: current_position + corrected_gamma + 1],
            past_key_values=target_cache,
            use_cache=use_cache,
        )
        target_cache = Mp.past_key_values
        target_logits = Mp.logits

        # rejection sampling
        n = corrected_gamma
        if use_greedy_sampler:
            target_token_ids = torch.argmax(target_logits, dim=-1)
            for i in range(corrected_gamma):
                if target_token_ids[0, i] != hl[i]:
                    n = i
                    break
                drafts_accepted += 1
        else:
            p = logits_processor(target_logits[0])
            r = torch.rand(corrected_gamma, device=target.device)
            p = p.float()
            fractions = p[:corrected_gamma, ...] / q
            for i in range(corrected_gamma):
                j = current_position + i + 1
                if r[i] > fractions[i, input_ids[0, j]]:
                    n = i
                    break
                drafts_accepted += 1
                if input_ids[0, j] == stop_tokens:
                    return input_ids[0, prompt_len:j + 1].tolist(), drafts_accepted, drafts_speculated

        # adjust distribution and sample replacement token
        if use_greedy_sampler:
            x = target_token_ids[0, n]
        else:
            if n == corrected_gamma:
                p_p = p[-1:, ...]
            else:
                if not skip_sample_adjustment:
                    p_p = max_fn(p[n:n+1, :] - q[n:n+1, :])
                else:
                    p_p = p[n, :]
            x = logits_processor.sample(p_p)

        if n != corrected_gamma:
            # prune the cache (works for both full and sparse)
            if use_cache:
                drafter_cache = prune_cache(drafter_cache, corrected_gamma - n - 1)
                target_cache = prune_cache(target_cache, corrected_gamma - n)
        else:
            # all drafts accepted: supplement drafter cache
            if use_sparse:
                pos_id = current_position + corrected_gamma
                position_ids = torch.tensor([[pos_id]], device=drafter.device)
            else:
                position_ids = None

            Mq = drafter(
                input_ids=input_ids[..., current_position + corrected_gamma: current_position + corrected_gamma + 1],
                past_key_values=drafter_cache,
                use_cache=use_cache,
                position_ids=position_ids,
            )
            drafter_cache = Mq.past_key_values

        if debug:
            generated = input_ids.clone().detach()

        input_ids[0, current_position + 1 + n : current_position + 1 + corrected_gamma] = pad_token_id
        input_ids[0, current_position + 1 + n] = x

        if debug:
            printing.speculative_step(tokenizer, generated, input_ids, n, prompt_len, tot_token_nums, corrected_gamma)

        tot_token_nums += n + 1

        if x == stop_tokens:
            if debug:
                printing.end_token_found(n)
            return input_ids[0, prompt_len:tot_token_nums].tolist(), drafts_accepted, drafts_speculated

    print(f"总共多少步: {step}")
    print(f"接受的tokens：{drafts_accepted}")
    return input_ids[0, prompt_len:].tolist(), drafts_accepted, drafts_speculated
